# v3 syntax
version: "3"

# Named volumes
volumes:
  # MySQL Data
  orm-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: orm-mysql
    volumes:
      - orm-mysql-data:/var/lib/mysql
    ports:
      - "3305:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=orm
      - MYSQL_DATABASE=orm
      - MYSQL_USER=orm
      - MYSQL_PASSWORD=orm
  # PHP (with Nginx)
  app:
    image: ambientum/php:7.2-nginx
    container_name: orm-app
    depends_on:
      - mysql
    volumes:
      - .:/var/www/app
    ports:
      - "8080:8080"
    links:
      - mysql
